POST  http://localhost:5000/SignupUser
Content-Type: application/json

{
   "firstName": "",
   "lastName": "",
   "email": "test123@gmail.com",
   "password": "test",
   "confirmpassword": "test",
   "image": "",
   "role": "human"
}


############################################ login part
POST http://localhost:5000/login
Content-Type: application/json

{
   "email": "admin@gmail.com",
   "password": "admin"
}