POST  http://localhost:5000/signupuser
Content-Type: application/json

{
   " firstName": "",
   "lastName": "",
   "email": "test@gmail.com",
   "password": "test",
   "image": ""
}

###
POST http://localhost:5000/login
Content-Type: application/json

{
   "email": "test@gmail.com",
   "password": "test"
}