POST  http://localhost:5000/SignupUser
Content-Type: application/json

{
   " firstName": "",
   "lastName": "",
   "email": "admin@gmail.com",
   "password": "admin",
   "image": ""
}


############################################ login part
POST http://localhost:5000/login
Content-Type: application/json

{
   "email": "admin@gmail.com",
   "password": "admin"
}